user:
  fullname:
    max_length: 50
user_project:
  title_max_length: 50
  description_max_length: 1000
company:
  name_max_length: 50
  description_max_length: 1000
  page_size: 6
  truncate_description: 100
image:
  max_size: 5
  acceptable_types: ["image/jpg", "image/jpeg", "image/png", "image/gif"]    
jobs:
  page_size: 4
  description_max_length: 100
  filter_locations: ["Hà Nội", "Đà Nẵng", "Hồ Chí Minh"]
  related_jobs_size: 5
interview:
  datetime_format: "%B %d, %Y %H:%M"
enterprise_scout:
  page_size: 12
roles:
  user: 0
  enterprise: 1
  admin: 2
