user:
  fullname:
    max_length: 50
  phone:
    format: /\A\+?[0-9]{10,14}\z/
user_project:
  title_max_length: 50
  description_max_length: 1000
company:
  name_max_length: 50
  description_max_length: 1000
image:
  max_size: 5
  acceptable_types: [".jpg", ".jpeg", ".png", ".gif"]    
jobs:
  page_size: 4
  description_max_length: 100
